// This file is auto-generated by @hey-api/openapi-ts

export { getGreeting, login, type Options } from './sdk.gen';
export type { ClientOptions, ErrorDetail, ErrorModel, ErrorModelWritable, GetGreetingData, GetGreetingError, GetGreetingErrors, GetGreetingResponse, GetGreetingResponses, GreetingOutputBody, GreetingOutputBodyWritable, LoginData, LoginError, LoginErrors, LoginRequest, LoginRequestWritable, LoginResponse, LoginResponseBody, LoginResponseBodyWritable, LoginResponses } from './types.gen';
