// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GreetingOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * The response of a greeting
     */
    msg: string;
};

export type LoginRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    Token: string;
};

export type LoginResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    Success: boolean;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GreetingOutputBodyWritable = {
    /**
     * The response of a greeting
     */
    msg: string;
};

export type LoginRequestWritable = {
    Token: string;
};

export type LoginResponseBodyWritable = {
    Success: boolean;
};

export type GetGreetingData = {
    body?: never;
    path: {
        user: string;
    };
    query?: never;
    url: '/greeting/{user}';
};

export type GetGreetingErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetGreetingError = GetGreetingErrors[keyof GetGreetingErrors];

export type GetGreetingResponses = {
    /**
     * OK
     */
    200: GreetingOutputBody;
};

export type GetGreetingResponse = GetGreetingResponses[keyof GetGreetingResponses];

export type LoginData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseBody;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];
